### ISSUE TITLE
How much of the editor interface could be exposed

### ISSUE THREAD

**Issue by RonFischer** [20tab/UnrealEnginePython#10] opened 2016-08-28 08:37 UTC
I'm interested in building up levels using Python scripts, not so much using Python in run mode.

Have tried reading the UE source base to find the editor classes. How much could be exposed to Python? Import to Content Browser with options set, import to World Outliner, again with options, etc.?

**Comment by rdeioris** [comment] 2016-08-28 08:48
Basically, anything you need, currently you can already build up levels:

```py
import unreal_engine as ue

editor = ue.get_world_editor()

my_actor_blueprint = ue.find_class('YourBlueprint')

editor.actor_spawn(my_actor_blueprint)
```

or import assets like described here:

https://github.com/20tab/UnrealEnginePython/blob/master/PythonConsole.md#asset-importing

**Comment by RonFischer** [comment] 2016-08-29 07:46
I'm trying it out now. Thank you for this work. 

A Python console is useful, but perhaps an easier start is a simple script shelf? I.e. a set of named buttons made from python files in a directory. Press one of the buttons and the script runs, with log output. When the script completes, the instance of the Python interpreter is deleted. 

For us, Python integration with Shotgun is the ultimate goal.

**Comment by rdeioris** [comment] 2016-08-29 08:06
You mean shotgun the collaboration tool ?

**Comment by RonFischer** [comment] 2016-08-29 08:43
Yes, http://www.shotgunsoftware.com/ and in particular the Shotgun Toolkit (formerly Tank). Shotgun acts as workflow and digital asset manager. The Shotgun API is useful to find FBX asset files in large productions, import and spawn them to build scene setups. Shotgun's Python toolkit module supports older 2.7, but there are several ways around this problem, or you might offer a 2.7 variation of this plugin ;-) 

Your plugin could be a useful gateway for many companies to do this. Thank you and I hope to contribute what I can.

**Comment by crispy4004** [comment] 2016-08-29 18:01
Not using Shotgun in production myself, we have our own custom PyQt Asset Manager/Build Tool and tracking tools, but I imagine you are looking to do the same we are, seamlessly import assets into the Engine from your management software and automate additional actions to or with those assets.

It is possible to open an RPC server within the Engine through Python and communicate with it from an outside Python console.  It's also possible to [trigger a new fbx import with the importer window](https://github.com/20tab/UnrealEnginePython/blob/master/PythonConsole.md#asset-importing).  What I'm not sure we can do yet is importing Fbx files silently in the background, setting options, and assigning physics assets and skeletons if applicable.  Also trigger a re-import on existing assets.

See today that 20tab added preliminary support for structs (thanks a bunch!), so maybe that opens up the possibilities.  Not sure yet.

**Comment by RonFischer** [comment] 2016-08-30 01:27
We came to the same conclusion about writing an RPC style service inside Unreal, thank you. 

The frontier for us is access to the new Sequence Editor, building up tracks, querying. There's a host of automation that's would be very useful in there to integrate with Avid or FCP editorial processes.

**Comment by rdeioris** [comment] 2016-08-30 16:40
Currently setting the skeleton is already working:

```py
skeleton = ue.find_object('UE4_Mannequin_Skeleton')
asset = ue.import_asset(filename, asset_name)
asset.set_property('Skeleton', skeleton)
```

eventually you can directly set the importer to assign the skeleton:

```py
factory = ue.find_class('FbxFactory')
factory_obj = ue.new_object(factory)
factory_obj.get_property('ImportUI').set_property('Skeleton', skeleton)
```

but the dialog (in both cases) is triggered. 

I am investigating if it can be disabled and rely only on properties.

**Comment by tonybarbieri** [comment] 2016-09-01 16:02
I have a prototype working where PySide is running within UE using python 2.7. An RPC server is probably not necessary to integrate with either Shotgun Toolkit or PyQt but I need to test more before I can confirm. With this working writing a Shotgun Toolkit Engine shouldn't be difficult. I have a separate project I've been working on this in but will look at forking this project and integrating my changes in. I'm not sure how different the API is between python 2.7 and python 3.5. I haven't used python 3 at all yet due to the applications we integrate with not having moved past 2.

**Comment by crispy4004** [comment] 2016-09-01 17:46
Very cool Tony, using Qt in Unreal would be soo helpful.  Would PyQt4/Sip in theory work as well?  We transitioned to PyQt after watching PySide development fall behind and take a long hiatus, though I believe Autodesk is more invested now in keeping it up to date.

**Comment by tonybarbieri** [comment] 2016-09-01 18:07
@crispy4004 PyQt/Sip should work fine. Nothing I am doing is PySide specific at all.

**Comment by RonFischer** [comment] 2016-09-01 23:59
Amazing! Thanks so much.

**Comment by rdeioris** [comment] 2016-09-02 09:08
@RonFischer I have started implementing the sequencer api. Do you have a specific workflow in mind i can base the work on ? Thanks

**Comment by rdeioris** [comment] 2016-09-02 10:34
I have added a section in the README for proper PyQT5 usage:

https://github.com/20tab/UnrealEnginePython/blob/master/README.md#integration-with-pyqt

**Comment by RonFischer** [comment] 2016-09-02 10:48
@rdeioris very kind of you to ask Robb. Traversing tracks, reading the target actor, traversing clips in the track, reading the media and adjust offsets. That is the start. 

I am amazed at your progress!

**Comment by tonybarbieri** [comment] 2016-09-02 15:43
@rdeioris Thank you for writing up the PyQT5 usage. We are going to need to do a bit more to ensure PyQT and PySide are both running and have all the features available (Signals being one of them). In your example a QtApplication event loop is never started. Because it's a blocking process what I've done in the past is to manually pump the event loop by hooking into a callback provided by the host application. In my tests that I've gotten to work I've passed a callback to FTicker with a repeat duration of zero. This seems to work but one caveat is I was then running into threading issues so in the C++ code I wrapped the python callback in a lambda whose body looked like:

`PyGILState_STATE gstate;
gstate = PyGILState_Ensure();
result = PYTHONCALLBACK
PyGILState_Release(gstate);
`

This lambda is then passed to the FTimer command. I'm not 100% sure this is the correct way to deal with it but it did stop the crashes I was getting from happening. I also needed to put similar code elsewhere such as around the python call in PythonConsole .

Another bit that will help with integration is exposing the Unreal Editor HWND so we can cast it and parent an invisible QtWidget to it which will act as a parent for the rest of the Qt UI elements. This allows Qt windows to stay on top of the Unreal Editor when they lose focus to another portion of the editor. This technique was used when integrating Qt with Softimage.

Ideally I can get these changes into your code and pushed up today along with the changes I made so python 2.7 can be used as well as a few additional tweaks and features which hopefully will be alright with you.

**Comment by RonFischer** [comment] 2016-09-18 08:13
@rdeioris in traversing the sequence editor folder I find a list of "child object binding strings" which appear to lead to the tracks (not the ChildMasterTracks property, which is what I expected). What are these "ChildObjectBindingStrings" and how do I traverse into them to get down to the clips and animation media?

**Comment by rdeioris** [comment] 2016-09-19 07:46
@RonFischer hi, honestly i am still trying to understand the sequencer implementation :) while tracks, sections and possessable are pretty clear at the high level, the classes tree looks a bit weird (probably because docs are still incomplete). I should be able to address it during this week

**Comment by RonFischer** [comment] 2016-09-19 08:16
Thanks Rob. I went through Sequencer classes API yesterday and will follow
up here with a summary for you.

**Comment by RonFischer** [comment] 2016-09-20 03:32
@rdeioris I've branched locally to add support for FMovieSceneBinding, which is the key missing piece connecting scene to track traversals. FMovieSceneBinding is a struct. Can you point out an example for making structs available at Python level? I've looked at FVector but think that may not be the best. Also, do you make Guids visible in Python? Or convert? Again, pointer to example from this codebase would be helpful. Hope I can contribute.

**Comment by rdeioris** [comment] 2016-09-20 07:10
You can access struct field with 

```
your_struct.properties()
```
and then 

```
your_struct.get_property('name')
```

I will check for guid soon. Thanks a lot for your pdf it clarified things a lot

**Comment by rdeioris** [comment] 2016-09-26 07:08
@RonFischer hi, i am closing this and opening another new one specific to the sequencer

**Closed** 2016-09-26 07:08 UTC
