### ISSUE TITLE
Casting FLinearColor to a string results in segfault

### ISSUE THREAD

**Issue by matthewkapfhammer** [20tab/UnrealEnginePython#108] opened 2017-01-20 00:00 UTC
Win 10
UE-4.14.3
UnrealEnginePython_20170117_4_14_python27.zip

```python
            if type(parameter_value) == ue.FLinearColor:
                ue.log(str(parameter_value))
```

Current workaround:
```python
            if type(parameter_value) == ue.FLinearColor:
                parameter_value = {
                    'r': parameter_value.r,
                    'g': parameter_value.g,
                    'b': parameter_value.b,
                    'a': parameter_value.a,
                }
                ue.log(str(parameter_value))
```

**Comment by rdeioris** [comment] 2017-01-23 18:58
Hi, cannot reproduce it with latest code. Do you have a traceback of the segfault ? Thanks

**Comment by matthewkapfhammer** [comment] 2017-01-24 20:32
Sure thing. Might be a day or so.

**Comment by matthewkapfhammer** [comment] 2017-02-01 00:53
From the Crash Reporter UI that pops up after the segfault:
```
Access violation - code c0000005 (first/second chance not available)

python27
python27
UE4Editor_UnrealEnginePython
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
python27
UE4Editor_UnrealEnginePython
UE4Editor_UnrealEnginePython
UE4Editor_Slate!FUICommandList::ExecuteAction() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\slate\private\framework\commands\uicommandlist.cpp:92]
UE4Editor_Slate!SMenuEntryBlock::OnClicked() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\slate\private\framework\multibox\smenuentryblock.cpp:1033]
UE4Editor_Slate!SMenuEntryBlock::OnMenuItemButtonClicked() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\slate\private\framework\multibox\smenuentryblock.cpp:993]
UE4Editor_Slate!TMemberFunctionCaller<SMenuEntryBlock,FReply (__cdecl SMenuEntryBlock::*)(void) __ptr64>::operator()<>() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\public\delegates\delegateinstanceinterface.h:161]
UE4Editor_Slate!TTupleImpl<TIntegerSequence<unsigned int> >::ApplyAfter<TMemberFunctionCaller<SMenuEntryBlock,FReply (__cdecl SMenuEntryBlock::*)(void) __ptr64> >() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\public\delegates\tuple.h:116]
UE4Editor_Slate!TBaseSPMethodDelegateInstance<0,SMenuEntryBlock,0,FReply __cdecl(void)>::Execute() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:318]
UE4Editor_Slate!TBaseDelegate<FReply>::Execute() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:522]
UE4Editor_Slate!SButton::OnMouseButtonUp() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\slate\private\widgets\input\sbutton.cpp:275]
UE4Editor_Slate!SMenuEntryButton::OnMouseButtonUp() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\slate\private\framework\multibox\smenuentryblock.cpp:391]
UE4Editor_Slate!<lambda_8d0e9a1da76abd0a756a3a9d775f5ed1>::operator()() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5010]
UE4Editor_Slate!FEventRouter::Route<FReply,FEventRouter::FToLeafmostPolicy,FPointerEvent,<lambda_8d0e9a1da76abd0a756a3a9d775f5ed1> >() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:215]
UE4Editor_Slate!FSlateApplication::RoutePointerUpEvent() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:4999]
UE4Editor_Slate!FSlateApplication::ProcessMouseButtonUpEvent() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5462]
UE4Editor_Slate!FSlateApplication::OnMouseUp() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5439]
UE4Editor_Core!FWindowsApplication::ProcessDeferredMessage() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\private\windows\windowsapplication.cpp:1652]
UE4Editor_Core!FWindowsApplication::DeferMessage() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\private\windows\windowsapplication.cpp:2071]
UE4Editor_Core!FWindowsApplication::ProcessMessage() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\private\windows\windowsapplication.cpp:814]
UE4Editor_Core!FWindowsApplication::AppWndProc() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\private\windows\windowsapplication.cpp:678]
user32
user32
UE4Editor_Core!FWindowsPlatformMisc::PumpMessages() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\private\windows\windowsplatformmisc.cpp:951]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\launch\private\launchengineloop.cpp:2811]
UE4Editor!GuardedMain() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\launch\private\launch.cpp:152]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:126]
UE4Editor!WinMain() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:202]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264]
kernel32
ntdll
```

**Comment by rdeioris** [comment] 2017-04-24 20:36
Should be fixed in latest release, close it if you can confirm it

**Closed** 2017-05-03 08:04 UTC
